replicaCount: 1
image:
  repository: gcr.io/google-samples/microservices-demo/cartservice
  tag: 8a162924b8eb066aa070e97d78ce5f36e2d271ca
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 7070
resources:
  requests:
    cpu: 200m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 128Mi
